/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './empty-text.module';
import * as i2 from './empty-text.service';
export const EmptyTextModuleNgFactory:i0.NgModuleFactory<i1.EmptyTextModule> = i0.ɵcmf(i1.EmptyTextModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.EmptyTextService,i2.EmptyTextService,([] as any[])),i0.ɵmpd(512,i1.EmptyTextModule,
          i1.EmptyTextModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHZleWV0L0Rlc2t0b3AvZW1wdHl0ZXh0L2xpYi9lbXB0eS10ZXh0Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy90dmV5ZXQvRGVza3RvcC9lbXB0eXRleHQvbGliL2VtcHR5LXRleHQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
